---
- name: restart nginx
  block:
  - name: restart nginx
    service: 
      name: nginx
      state: restarted
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
  become: true
  become_user: root
